name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: agiletec-inc/.github/.github/workflows/node-pnpm-ci.yml@main
    with:
      node-version: '22'
      run-command: pnpm turbo run build lint test
