name: CI
on:
  pull_request:
  merge_group:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  secret-scan:
    uses: agiletec-inc/.github/.github/workflows/secret-scan.yml@main
  ci:
    uses: agiletec-inc/.github/.github/workflows/node-pnpm-ci.yml@main
